### PR TITLE
Remove Walmart from hardware providers

### PR DESCRIPTION
**Pull request by jbergstroem**
Walmart temporarily provided hardware (hat tip Wyatt Preul <wpreul@gmail.com>) which were replaced by VMs from Joyent.

With this merged I'll also remove the slave from Jenkins.

/R=@geek

### CODE REVIEW

**Comment by geek** [comment]
LGTM.  Thank you, @joyent

**Comment by bnoordhuis** [comment]
LGTM

**Comment by wblankenship** [comment]
:+1: thank you @joyent :smile:

**Comment by jbergstroem** [comment]
Merged in c2968712842151a32caeccf4ff693f26d458f6dc and removed the node from jenkins. Thanks for the Review.

**Pull request closed without merging**
