### PR TITLE
smartos: enable building with ccache

### PR DESCRIPTION
**Pull request by jbergstroem**
We need to symlink ourselves since the package manager doesn't do it for us.

Edit: This PR also requires jenkins master to be restarted (See #89 for link)

### CODE REVIEW

**Comment by rvagg** [comment]
Cool, lgtm.

Does the install process for ccache on smartos not make symlinks itself? I'm finding for newer linux distros it's all taken care of automatically.

re restarting Jenkins, I think you have access to do that via the Jenkins interface, otherwise ping me and I can do it manually on the server.

**Comment by jbergstroem** [comment]
@rvagg nope -- symlinking has to be taken care of manually. I've updated to the newest pkg repo on my local smartos machines and it seems like we might have to do some path changes forward as well. No biggie though.

As for Jenkins, thanks for letting me know. I'd rather have you do it this time since it's somewhat voodoo. He's probably already annoyed with me.

I'll merge this and #89 if you think that looks good as well and then we'll update/restart.

**Comment by jbergstroem** [comment]
Merged in 46d79036f09a488e13422300b30599fe007117cb . Thanks for reviewing (and doing it so quickly).

**Comment by jbergstroem** [comment]
Found a typo. Crap. `s|/usr/local/libexec|/opt/local/libexec|g`..

**Pull request closed without merging**
